services:
  app:
    image: super-benchmark:latest
    env_file: .env
    restart: always
    container_name: benchmark
    command: /bin/bash -c "uvicorn app.main:app --reload --host 0.0.0.0 --port ${PORT} --proxy-headers"
    user: root
    ports:
      - ${PORT}:8000
    volumes:
      - ./:/code/
